### PR TITLE
CI: Add a GitHub Actions matrix

### PR DESCRIPTION
**Pull request by olleolleolle**
This PR adds a GitHub Actions configuration. And gets the test suite to green.

## TODO

- [x] Update the gem version to 1.0 for a first intentional break (if you agree, I'm not a versioning expert)
- [x] List supported Rails versions in the README (or, technically, ActiveSupport version as Rails is just a likely use case)
- [x] Update the ActiveSupport dependency in the gemspec (I think this should prevent old Rails apps accidentally using the new version and breaking without warning)

## Details

I picked Ruby 3.1+ and Rails 7.0+ for the test matrix.

There were test failures, I could see them in my repo (not yet in this repo). Example: https://github.com/olleolleolle/paypal-express/actions/runs/10683175551/job/29610652302

**Update**: it was possible to fix them, and I named the test runs so that it's easier to pick out which versions are tested.

image

### CODE REVIEW

**Comment by ianfleeton** [comment]
Hi - thanks for this. However I wasn't going to pull earlier versions of Rails just yet. In my work in progress I had this:
```
         self.start_date = if self.start_date.respond_to?(:to_fs)
           self.start_date.to_fs(:db)
         else
           self.start_date.to_s(:db)
         end
```
What do you think? And we can still support versions prior? (I paused due to the old Travis test matrix not being set up properly anymore.)

**Comment by olleolleolle** [comment]
@ianfleeton If you wish to continue to support EOL Ruby versions, that’s alright, go for it! The code snippet looks good to me.

**Comment by ianfleeton** [comment]
Thanks for your comment which got me thinking more and changing my mind.

My goal is to serve the users of this library and I'm guessing a portion of the users of this library will be older projects which is why all changes so far have been minimal and conservative.

However, with no new functionality changes being made there is no loss for EOL Rails users to pin to an older gem version.

So I'm going to backtrack and suggest these tweaks to the PR instead:

- [ ] Keep your suggested fix for simplicity
- [ ] Update the gem version to 1.0 for a first intentional break (if you agree, I'm not a versioning expert)
- [ ] List supported Rails versions in the README (or, technically, ActiveSupport version as Rails is just a likely use case)
- [ ] Update the ActiveSupport dependency in the gemspec (I think this should prevent old Rails apps accidentally using the new version and breaking without warning)

Thanks again for the contribution!

**Comment by olleolleolle** [comment]
Agreeing with this plan! Fruitful disagreement led to harmony!

**Comment by olleolleolle** [comment]
@ianfleeton I now made the changes.

If you really want me to bump the version number, myself, I did a commit with that.

**Pull request merged**
